modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile = "logo.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/botany-pots-ore-planting"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="botanypots"
mandatory=true
versionRange="${botanypots_version}"
ordering="NONE"
side="BOTH"
